services:
  db:
    image: mysql:8.0
    container_name: nse_mysql
    restart: always
    environment:
      MYSQL_DATABASE: nse_portfolio
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3316:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: nse_django_api
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=nse_portfolio
      - DB_USER=root
      - DB_PASSWORD=password
      - PYTHONPATH=/app
    depends_on:
      - db

  bot:
    build: .
    container_name: nse_telegram_bot
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=nse_portfolio
      - DB_USER=root
      - DB_PASSWORD=password
      - PYTHONPATH=/app
    depends_on:
      - db
      - api
    command: python nse_bot.py

volumes:
  mysql_data:
