# Generated by Django 5.0.14 on 2026-02-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='1', max_length=100)),
                ('ticker', models.CharField(max_length=20)),
                ('qty', models.FloatField(default=0.0)),
                ('avg_cost', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trades',
                'unique_together': {('user_id', 'ticker')},
            },
        ),
    ]
