# Generated by Django 5.0.14 on 2026-04-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_bonus_requests_topup_dailyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bot_portfolio_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
